#!/bin/bash
# This is a fun PS1 that adds some emotion to the command line. Successful,
# failed, missing, and aborted commands all have their own unique emotion.
# If you ever find yourself teaching Linux, this can actually serve as a bit
#   of tangential learning; it begs questions that guide you towards a
#   discussion about the exciting world of exit codes and case statements!

# Formatting.
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 6)
WHITE=$(tput setaf 7)
BOLD=$(tput bold)
NF=$(tput sgr0) #No Formatting.

function emoticon {
  case $? in
  0)
    # Previous command was successful.
    echo "${GREEN};) "
    ;;
  127)
    # Previous command not found.
    echo "${BLUE}%) "
    ;;
  130)
    # Previous command terminated with Ctrl-C.
    echo "${YELLOW}:| "
    ;;
  *)
    # Some other unspecified error.
    echo "${RED}:( "
    ;;
  esac
}

export PS1="\[${BOLD}\]\[${WHITE}\][\[${GREEN}\]\u@\h\[${WHITE}\]]:\[${BLUE}\]\W\[${WHITE}\] \[${RED}\]\$(emoticon)\[${WHITE}\]\$ \[${NF}\]"
